### ISSUE TITLE
Не ставится тарс кли

### ISSUE THREAD

**Issue by DjSunrise** [tars/tars-cli#78]
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\AlibekKulseitov\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\AlibekKulseitov\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\AlibekKulseitov\AppData\Roaming\npm\node_modules\tars-cli\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AlibekKulseitov\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\AlibekKulseitov\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.14 (node_modules\tars-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\tars-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: posix@4.1.1 (node_modules\tars-cli\node_modules\posix):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: posix@4.1.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\AlibekKulseitov\AppData\Roaming\npm\node_modules\tars-cli\node_modules\scss-tokenizer\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\AlibekKulseitov\AppData\Roaming\npm\node_modules\tars-cli\node_modules\scss-tokenizer\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Users\\AlibekKulseitov\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\scss-tokenizer\\node_modules' }
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AlibekKulseitov\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "tars-cli"
npm ERR! node v8.9.4
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\AlibekKulseitov\AppData\Roaming\npm-cache\_logs\2018-02-13T12_43_44_560Z-debug.log

**Comment by SvetaVP** [comment]
У меня тоже самое пишет

**Comment by DjSunrise** [comment]
@SvetaVP я решил проблему установкой node 7.0.0 https://nodejs.org/dist/
Конечно не желательно старые версии устанавливать но я не могу без тарса работать

**Comment by SvetaVP** [comment]
Спасибо за совет, у меня тоже получилось)))

**Comment by ericssan** [comment]
Npm сообщает что не может найти питон установленный, соответственно не работает node-gyp.

Все происходит потому что на винде недостаточно просто установить питон, надо еще поставить такую [штуку.](https://www.npmjs.com/package/windows-build-tools)

**Comment by SvetaVP** [comment]
возникла необходимость поставить тарс на другую машину выдает ошибку:
 PS E:\1> npm i -g tars-cli
npm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.co
m/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn
-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versio
ns of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future version
s of Node.js
npm WARN deprecated gulp-util@0.0.1: gulp-util is deprecated - replace it, following the guidelines at https://medium.co
m/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated jade@1.9.2: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.co
m/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
C:\Users\CoZ\AppData\Roaming\npm\tars -> C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\bin\tars.js

> uws@9.14.0 install C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> phantomjs@1.9.20 install C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\phantomjs
> node install.js

PhantomJS not found on PATH
Download already available at C:\Users\CoZ\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\CoZ\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1520094271393\pha
ntomjs-1.9.8-windows -> C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\phantomjs\lib\ph
antom\phantomjs.exe

> node-sass@3.13.1 install C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> posix@4.1.1 install C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\posix
> node-gyp rebuild


C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\posix>if not defined npm_config_node_gyp (node "C:\P
rogram Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.j
s" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
MSBUILD : error MSB3428: Загрузка компонента Visual C++ "VCBuild.exe" невозможна. Способы решения проблемы: 1) установк
а .NET Framework 2.0 SDK, 2) установка Microsoft Visual Studio 2005 или 3) указание адреса компонента в системном пути,
 если компонент установлен в другом месте.  [C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\posix\
build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
58:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\posix
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> spawn-sync@1.0.15 postinstall C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\spawn-sync
> node postinstall


> node-sass@3.13.1 postinstall C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-gyp\
bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\node-gyp\\bin\\node-gyp.js'
,
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\whi
ch\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\which\which.js:68:
19)
gyp verb `which` failed     at E (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\which\which.js:80:
29)
gyp verb `which` failed     at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\isexe\windows.js:36:5

gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\whi
ch\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\which\which.js:68:
19)
gyp verb `which` failed     at E (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\which\which.js:80:
29)
gyp verb `which` failed     at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\isexe\windows.js:36:5

gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\CoZ\\AppData\\Roaming\\
npm\\node_modules\\tars-cli\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node
_modules\\tars-cli\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\
\tars-cli\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\n
ode_modules\\which\\which.js:89:16\n    at C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\
isexe\\index.js:42:5\n    at C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\isexe\\windows
.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\whi
ch\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\which\which.js:68:
19)
gyp verb `which` failed     at E (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\which\which.js:80:
29)
gyp verb `which` failed     at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\isexe\windows.js:36:5

gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\whi
ch\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\which\which.js:68:
19)
gyp verb `which` failed     at E (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\which\which.js:80:
29)
gyp verb `which` failed     at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\isexe\windows.js:36:5

gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Users\\CoZ\\AppData\\Roaming\\n
pm\\node_modules\\tars-cli\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_
modules\\tars-cli\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\
tars-cli\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\no
de_modules\\which\\which.js:89:16\n    at C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\i
sexe\\index.js:42:5\n    at C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\isexe\\windows.
js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned:
 "2.7.14\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.4
gyp verb command install [ '8.9.4' ]
gyp verb install input version string "8.9.4"
gyp verb install installing version: 8.9.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.4
gyp verb build dir attempting to create "build" dir: C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules
\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules
\node-sass\build
gyp verb Not using VS2017: Could not use PowerShell to find VS2017
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\
node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-sa
ss\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-sa
ss\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\node-gyp\\gyp\\gyp_m
ain.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\node-sass\\build\\co
nfig.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\node-gyp\\addon.gypi
',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\CoZ\\.node-gyp\\8.9.4\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\CoZ\\.node-gyp\\8.9.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\node-
gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\CoZ\\.node-gyp\\8.9.4\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\no
de-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\CoZ\.node-gyp\8.9.4
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
Сборка начата 03.03.2018 18:24:37.
Проект "C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-sass\build\binding.sln" в узле 1 (целе
вые объекты по умолчанию).
ValidateSolutionConfiguration:
  Создание конфигурации решения "Release|x64".
MSBUILD : error MSB3428: Загрузка компонента Visual C++ "VCBuild.exe" невозможна. Способы решения проблемы: 1) установк
а .NET Framework 2.0 SDK, 2) установка Microsoft Visual Studio 2005 или 3) указание адреса компонента в системном пути,
 если компонент установлен в другом месте.  [C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-s
ass\build\binding.sln]
Сборка проекта "C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-sass\build\binding.sln" заверш
ена (целевые объекты по умолчанию) с ошибкой.


Ошибка сборки.

"C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-sass\build\binding.sln" (целевой объект по ум
олчанию) (1) ->
(Целевой объект _src_\libsass) ->
  MSBUILD : error MSB3428: Загрузка компонента Visual C++ "VCBuild.exe" невозможна. Способы решения проблемы: 1) устано
вка .NET Framework 2.0 SDK, 2) установка Microsoft Visual Studio 2005 или 3) указание адреса компонента в системном пут
и, если компонент установлен в другом месте.  [C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node
-sass\build\binding.sln]

    Предупреждений: 0
    Ошибок: 1

Затраченное время: 00:00:00.07
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-gyp\
lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\CoZ\\AppData\\Roaming\\npm\\node_modules\\tars-cli\\n
ode_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
 "--libsass_library="
gyp ERR! cwd C:\Users\CoZ\AppData\Roaming\npm\node_modules\tars-cli\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\tars-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: posix@4.1.1 (node_modules\tars-cli\node_modules\posix):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: posix@4.1.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\CoZ\AppData\Roaming\npm-cache\_logs\2018-03-03T16_25_00_082Z-debug.log
PS E:\1> 


Что это значит?  .NET Framework 2.0 SDK стоит

**Comment by mshlmv** [comment]
Инструкция для Windows: https://github.com/nodejs/node-gyp#on-windows

**Comment by SvetaVP** [comment]
спасибо, получилось.
